class BaseAnchovyException(Exception): ...
class BadEnvironmentVariable(BaseAnchovyException): ...
class AnchovyExecutionTimeout(BaseAnchovyException, TimeoutError): ...
class AnchovyPluginNotFound(BaseAnchovyException): ...
class AnchovyMissingConnection(BaseAnchovyException): ...
# class DatastoreKeyMissError(BaseAnchovyException): ...
class NoCheckpoint(BaseAnchovyException): ...
class ExpectedJsonCompatibleType(BaseAnchovyException): ...
class AnchovyStreamingError(BaseAnchovyException, RuntimeError): ...
class BrokenContext(BaseAnchovyException): ...
class BrokenConfig(BaseAnchovyException, RuntimeError): ...
class BadMagicImport(BaseAnchovyException, ImportError): ...
class TaskCallbackFailedWarning(Warning): ...
